config/routes.rb
Rails.application.routes.draw do
  root 'orders#index'
  resources :employee_territories
  resources :customer_customer_demographics
  resources :order_details
  resources :customer_demographics
  resources :territories
  resources :regions
  resources :orders
  resources :employees
  resources :customers
  resources :categories
  resources :shippers
  resources :suppliers
  resources :products
end

app/models/employee.rb
class Employee < ApplicationRecord
  self.primary_key = 'EmployeeID'

  before_validation(on: :create) { bump_id }

  belongs_to :supervisor, class_name: 'Employee', foreign_key: 'ReportsTo'
  has_many :subordinates, class_name: 'Employee', foreign_key: 'ReportsTo'

  has_many :orders

  has_and_belongs_to_many :territories, join_table: 'employeeterritories', \
    foreign_key: 'EmployeeID', association_foreign_key: 'TerritoryID' do
    def ids
      self.each_with_object([]) do |territory, territories_ids|
        territories_ids << territory.TerritoryID
      end
    end
  end

  def full_name
    [self.FirstName, self.LastName].join(' ')
  end

  def supervisor_name
    if supervisor && self_not_supervisor
      supervisor.full_name
    else
      '-'
    end
  end

  def supervisor_or_self_id
    supervisor ? supervisor.EmployeeID : self.EmployeeID
  end

  def formatted_territories
    territories.each_with_object([]) do |territory, territories|
      territories << territory_with_region(territory)
    end.join(',')
  end

  private

  def self_not_supervisor
    supervisor.full_name != self.full_name
  end

  def territory_with_region(territory)
    '%s(%s)' %
        [territory.TerritoryDescription, territory.region.RegionDescription]
  end

  def bump_id
    self.EmployeeID = Employee.maximum('EmployeeID') + 1
  end
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :find_employee, only: [:show, :edit, :update, :destroy]
  before_action :find_employees, only: [:index, :create, :edit, :update, :new]
  before_action :find_territories, only: [:create, :edit, :update, :new]

  def index
  end

  def show
  end

  def new
    @employee = Employee.new
  end

  def edit
    # byebug
  end

  def create
    @employee = Employee.new(employee_params)

    respond_to do |format|
      if @employee.save
        format.html { redirect_to @employee,
                                  notice: 'Employee was successfully created.' }
        format.json { render :show, status: :created, location: @employee }
      else
        format.html { render :new }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @employee.update(employee_params)
        format.html { redirect_to @employee,
                                  notice: 'Employee was successfully updated.' }
        format.json { render :show, status: :ok, location: @employee }
      else
        format.html { render :edit }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @employee.destroy
    respond_to do |format|
      format.html { redirect_to employees_url,
                                notice: 'Employee was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Never trust parameters from the scary internet, only allow the white list through.
  def employee_params
    params.require(:employee).permit(:LastName, :FirstName, :Title,
                                     :TitleOfCourtesy, :BirthDate, :HireDate,
                                     :Address, :City, :Region, :PostalCode,
                                     :Country, :HomePhone, :Extension, :Photo,
                                     :Notes, :PhotoPath, :ReportsTo,
                                     :EmployeeID,
                                     territory_ids: [])
  end

  def find_employee
    @employee = Employee.find(params[:id])
  end

  def find_territories
    @all_territories = Territory.all
    @territories_with_description =
        @all_territories.map { |territory|
          [territory.TerritoryDescription, territory.TerritoryID]
        }
  end

  def find_employees
    @all_employees = Employee.all.includes(territories: [:region])
  end
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/views/employees/_form.html.erb
<%= form_for(employee) do |f| %>
    <% if employee.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(employee.errors.count, "error") %> prohibited this
            employee from being saved:</h2>

          <ul>
            <% employee.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :LastName %>
      <%= f.text_field :LastName %>
    </div>

    <div class="field">
      <%= f.label :FirstName %>
      <%= f.text_field :FirstName %>
    </div>

    <!--options_for_select(-->
    <!--@employees_with_names,-->
    <!--# .select { |e| employee.EmployeeID != e.EmployeeID }-->
    <!--selected: employee.supervisor_or_self_id-->
    <!--),-->
    <div class="field">
      <%= f.label :Supervisor %>
      <%= f.collection_select :ReportsTo,
                   @all_employees, :EmployeeID, :full_name,
                   {prompt: 'Please select'}
      %>
    </div>

    <div class="field">
      <%= f.label 'Select Employee Territories:' %>
      <%= f.select :territory_ids,
                   options_for_select(
                       @territories_with_description,
                       selected: @employee.territories.ids),
                   {prompt: 'Please select'},
                   {multiple: true, size: 10}
            %>
    </div>

    <div class="field">
      <%= f.label :Title %>
      <%= f.text_field :Title %>
    </div>

    <div class="field">
      <%= f.label :TitleOfCourtesy %>
      <%= f.text_field :TitleOfCourtesy %>
    </div>

    <div class="field">
      <%= f.label :BirthDate %>
      <%= f.date_select :BirthDate %>
    </div>

    <div class="field">
      <%= f.label :HireDate %>
      <%= f.date_select :HireDate %>
    </div>

    <div class="field">
      <%= f.label :Address %>
      <%= f.text_field :Address %>
    </div>

    <div class="field">
      <%= f.label :City %>
      <%= f.text_field :City %>
    </div>

    <div class="field">
      <%= f.label :Region %>
      <%= f.text_field :Region %>
    </div>

    <div class="field">
      <%= f.label :PostalCode %>
      <%= f.text_field :PostalCode %>
    </div>

    <div class="field">
      <%= f.label :Country %>
      <%= f.text_field :Country %>
    </div>

    <div class="field">
      <%= f.label :HomePhone %>
      <%= f.telephone_field :HomePhone %>
    </div>

    <div class="field">
      <%= f.label :Extension %>
      <%= f.text_field :Extension %>
    </div>

    <div class="field">
      <%= f.label :Photo %>
      <%= f.text_field :Photo %>
    </div>

    <div class="field">
      <%= f.label :Notes %>
      <%= f.text_field :Notes %>
    </div>

    <div class="field">
      <%= f.label :PhotoPath %>
      <%= f.file_field :PhotoPath %>
    </div>

    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/employees/edit.html.erb
<h1>Editing Employee</h1>

<%= render 'form', employee: @employee %>

<%= link_to 'Show', @employee %> |
<%= link_to 'Back', employees_path %>

app/views/employees/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Employees</h1>

<%= link_to 'New Employee', new_employee_path %>
<br>
<br>

<table>
  <thead>
  <tr>
    <th colspan="3"></th>
    <th>Lastname</th>
    <th>Firstname</th>
    <th>Supervisor</th>
    <th style="width: 100px;">Territories</th>
    <th>Title</th>
    <th>Titleofcourtesy</th>
    <th>Birthdate</th>
    <th>Hiredate</th>
    <th>Address</th>
    <th>City</th>
    <th>Region</th>
    <th>Postalcode</th>
    <th>Country</th>
    <th>Homephone</th>
    <th>Extension</th>
    <th>Photo</th>
    <!--<th>Notes</th>-->
    <th>Photopath</th>
  </tr>
  </thead>

  <tbody>
  <% @all_employees.each do |employee| %>
      <tr>
        <td><%= link_to 'Show', employee %></td>
        <td><%= link_to 'Edit', edit_employee_path(employee) %></td>
        <td><%= link_to 'Destroy', employee, method: :delete, data: {confirm: 'Are you sure?'} %></td>
        <td><%= employee.LastName %></td>
        <td><%= employee.FirstName %></td>
        <td><%= employee.supervisor_name %></td>
        <td><%= employee.formatted_territories %></td>
        <td><%= employee.Title %></td>
        <td><%= employee.TitleOfCourtesy %></td>
        <td><%= employee.BirthDate %></td>
        <td><%= employee.HireDate %></td>
        <td><%= employee.Address %></td>
        <td><%= employee.City %></td>
        <td><%= employee.Region %></td>
        <td><%= employee.PostalCode %></td>
        <td><%= employee.Country %></td>
        <td><%= employee.HomePhone %></td>
        <td><%= employee.Extension %></td>
        <td><%= employee.Photo %></td>
        <!--<td><%= employee.Notes %></td>-->
        <td><%= employee.PhotoPath %></td>
      </tr>
  <% end %>
  </tbody>
</table>

app/views/employees/new.html.erb
<h1>New Employee</h1>

<%= render 'form', employee: @employee %>

<%= link_to 'Back', employees_path %>

app/views/employees/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Lastname:</strong>
  <%= @employee.LastName %>
</p>

<p>
  <strong>Firstname:</strong>
  <%= @employee.FirstName %>
</p>

<p>
  <strong>Supervisor:</strong>
  <%= @employee.supervisor_name %>
</p>

<p>
  <strong>Territories:</strong>
  <%= @employee.formatted_territories %>
</p>

<p>
  <strong>Title:</strong>
  <%= @employee.Title %>
</p>

<p>
  <strong>Titleofcourtesy:</strong>
  <%= @employee.TitleOfCourtesy %>
</p>

<p>
  <strong>Birthdate:</strong>
  <%= @employee.BirthDate %>
</p>

<p>
  <strong>Hiredate:</strong>
  <%= @employee.HireDate %>
</p>

<p>
  <strong>Address:</strong>
  <%= @employee.Address %>
</p>

<p>
  <strong>City:</strong>
  <%= @employee.City %>
</p>

<p>
  <strong>Region:</strong>
  <%= @employee.Region %>
</p>

<p>
  <strong>Postalcode:</strong>
  <%= @employee.PostalCode %>
</p>

<p>
  <strong>Country:</strong>
  <%= @employee.Country %>
</p>

<p>
  <strong>Homephone:</strong>
  <%= @employee.HomePhone %>
</p>

<p>
  <strong>Extension:</strong>
  <%= @employee.Extension %>
</p>

<p>
  <strong>Photo:</strong>
  <%= @employee.Photo %>
</p>

<p>
  <strong>Notes:</strong>
  <%= @employee.Notes %>
</p>

<p>
  <strong>Photopath:</strong>
  <%= @employee.PhotoPath %>
</p>

<%= link_to 'Edit', edit_employee_path(@employee) %> |
<%= link_to 'Back', employees_path %>